name: Check Temperature

on:
  push:
    branches:
      - main  
  workflow_dispatch: {}  # Add workflow dispatch for manual triggering
  schedule:
    - cron: '54 9 * * *'   # 09:00 (UTC) daily
    - cron: '54 12 * * *'   # 12:00 (UTC) daily
    - cron: '54 17 * * *'   # 17:00 (UTC) daily

jobs:
  Check-Temperature:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install Chromedriver and Chrome
        run: |
          echo "Installing system dependencies for Chrome/ChromeDriver..."
          # (Removed problematic packages libgconf-2-4 and libasound2)
          sudo apt-get install -y wget unzip gnupg libnss3 libxss1 libgtk-3-0 libatk-bridge2.0-0 libatk1.0-0 libx11-xcb1 --no-install-recommends
          
          echo "Downloading and Installing Google Chrome v133.0.6943.98..."
          CHROME_VERSION="133.0.6943.98"
          wget -O /tmp/chrome-linux64.zip "https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chrome-linux64.zip"
          
          # Extract Chrome binary
          sudo unzip -o /tmp/chrome-linux64.zip -d /opt/google/chrome/
          sudo ln -sf /opt/google/chrome/chrome /usr/bin/google-chrome
          
          echo "Installed Google Chrome version:"
          google-chrome --version
          
          # echo "Installing ChromeDriver for Chrome v104..."
          # Retrieve the latest ChromeDriver version for Chrome 104
          # CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_104)
          # echo "Using ChromeDriver version: ${CHROME_DRIVER_VERSION}"
          
          echo "Using ChromeDriver version: 133.0.6943.98"
          # wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
          wget -O /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.98/linux64/chromedriver-linux64.zip
          
          sudo unzip -o /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
          echo "Installed ChromeDriver version:"
          sudo /usr/local/bin/chromedriver --version
    
      - name: Install dependencies
        run: |
          git config user.email "luckyodi310@gmail.com"
          git config user.name "Nnamdi Odi"
          python -m pip install --upgrade pip
          python -m pip install "dask[distributed]" --upgrade
          pip install -r requirements.txt

      - name: Run Scrapper
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          USER: ${{ secrets.USER }}
          PASSWORD_: ${{ secrets.PASSWORD_ }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

        run: |
          python test.py          

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "::set-output name=changes::true"

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git pull
          git add .
          git commit -m "Scraped emails"
          git remote set-url origin https://$API_TOKEN@github.com/nnamdiindu/OLT_Temperature_Update.git
          git push
